services:
- type: web
  env: static
  name: gatorfly-frontend  
  buildCommand: npm run build
  staticPublishPath: ./dist  
  routes:
    - type: rewrite
      source: /**/*
      destination: /index.html
